### ISSUE TITLE
Erro!

### ISSUE THREAD

**Issue by andreiwd** [gerencianet/gn-api-boxbilling#1]
Instalei o módulo, configurei de acordo com as instruções... Porém ao tentar efetuar um pagamento, recebo o erro 
Gerencianet Erro
Para que o boleto da Gerencianet seja gerado é necessário que o cliente nos forneça CPF, caso queira fazer uma compra como Pessoa Física, ou CNPJ, caso queira fazer uma compra como Pessoa Jurídica. Esta exigência se tornou necessária para seguir as normas da Febraban e do Banco central para emissão de boletos. Assim, após fornecer seu CPF ou CNPJ, basta clicar no botão "Boleto". Se todas as informações repassadas no momento da compra estiverem corretas o boleto será gerado normalmente.

Logo abaixo, aparece o campo para digitar o CPF, porém, o botão "Boleto" fica sem ação... 

Tentei criar um campo personalizado no cadastro chamado CPF que recebeu o nome de "custom_1" no banco de dados, teria como passar esse campo para a API e contornar esse erro ? como faria isso?

Abraço

**Comment by chuckbnorris** [comment]
@andreiwd 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Por envolver requisições da API que estão presentes em sua conta Gerencianet, além de possuir informações pessoais (como dados cadastrais), o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Por aqui não é possível localizar seu cadastro conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Não esqueça de fornecer o máximo de informações no ticket, como por exemplo, versão do PHP, versão do Box Billing, número da(s) transação(ões) envolvida(s) e demais informações que julgar pertinentes.

Qualquer coisa, estou à disposição.

**Comment by andreiwd** [comment]
Obrigado @tiagoxpl !
Já foi resolvido junto ao suporte da GN. O módulo já está em pleno funcionamento...
